// source: Client.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Protobuf.Client.EntityMove');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Protobuf.Quaternion');
goog.require('proto.Protobuf.Vector2');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protobuf.Client.EntityMove = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protobuf.Client.EntityMove, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protobuf.Client.EntityMove.displayName = 'proto.Protobuf.Client.EntityMove';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protobuf.Client.EntityMove.prototype.toObject = function(opt_includeInstance) {
  return proto.Protobuf.Client.EntityMove.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protobuf.Client.EntityMove} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protobuf.Client.EntityMove.toObject = function(includeInstance, msg) {
  var f, obj = {
    entityuuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    position: (f = msg.getPosition()) && proto.Protobuf.Vector2.toObject(includeInstance, f),
    targetposition: (f = msg.getTargetposition()) && proto.Protobuf.Vector2.toObject(includeInstance, f),
    rotation: (f = msg.getRotation()) && proto.Protobuf.Quaternion.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protobuf.Client.EntityMove}
 */
proto.Protobuf.Client.EntityMove.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protobuf.Client.EntityMove;
  return proto.Protobuf.Client.EntityMove.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protobuf.Client.EntityMove} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protobuf.Client.EntityMove}
 */
proto.Protobuf.Client.EntityMove.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntityuuid(value);
      break;
    case 2:
      var value = new proto.Protobuf.Vector2;
      reader.readMessage(value,proto.Protobuf.Vector2.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    case 3:
      var value = new proto.Protobuf.Vector2;
      reader.readMessage(value,proto.Protobuf.Vector2.deserializeBinaryFromReader);
      msg.setTargetposition(value);
      break;
    case 4:
      var value = new proto.Protobuf.Quaternion;
      reader.readMessage(value,proto.Protobuf.Quaternion.deserializeBinaryFromReader);
      msg.setRotation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protobuf.Client.EntityMove.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protobuf.Client.EntityMove.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protobuf.Client.EntityMove} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protobuf.Client.EntityMove.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntityuuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Protobuf.Vector2.serializeBinaryToWriter
    );
  }
  f = message.getTargetposition();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.Protobuf.Vector2.serializeBinaryToWriter
    );
  }
  f = message.getRotation();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.Protobuf.Quaternion.serializeBinaryToWriter
    );
  }
};


/**
 * optional string EntityUUID = 1;
 * @return {string}
 */
proto.Protobuf.Client.EntityMove.prototype.getEntityuuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protobuf.Client.EntityMove} returns this
 */
proto.Protobuf.Client.EntityMove.prototype.setEntityuuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Protobuf.Vector2 Position = 2;
 * @return {?proto.Protobuf.Vector2}
 */
proto.Protobuf.Client.EntityMove.prototype.getPosition = function() {
  return /** @type{?proto.Protobuf.Vector2} */ (
    jspb.Message.getWrapperField(this, proto.Protobuf.Vector2, 2));
};


/**
 * @param {?proto.Protobuf.Vector2|undefined} value
 * @return {!proto.Protobuf.Client.EntityMove} returns this
*/
proto.Protobuf.Client.EntityMove.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protobuf.Client.EntityMove} returns this
 */
proto.Protobuf.Client.EntityMove.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protobuf.Client.EntityMove.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Protobuf.Vector2 TargetPosition = 3;
 * @return {?proto.Protobuf.Vector2}
 */
proto.Protobuf.Client.EntityMove.prototype.getTargetposition = function() {
  return /** @type{?proto.Protobuf.Vector2} */ (
    jspb.Message.getWrapperField(this, proto.Protobuf.Vector2, 3));
};


/**
 * @param {?proto.Protobuf.Vector2|undefined} value
 * @return {!proto.Protobuf.Client.EntityMove} returns this
*/
proto.Protobuf.Client.EntityMove.prototype.setTargetposition = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protobuf.Client.EntityMove} returns this
 */
proto.Protobuf.Client.EntityMove.prototype.clearTargetposition = function() {
  return this.setTargetposition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protobuf.Client.EntityMove.prototype.hasTargetposition = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Protobuf.Quaternion Rotation = 4;
 * @return {?proto.Protobuf.Quaternion}
 */
proto.Protobuf.Client.EntityMove.prototype.getRotation = function() {
  return /** @type{?proto.Protobuf.Quaternion} */ (
    jspb.Message.getWrapperField(this, proto.Protobuf.Quaternion, 4));
};


/**
 * @param {?proto.Protobuf.Quaternion|undefined} value
 * @return {!proto.Protobuf.Client.EntityMove} returns this
*/
proto.Protobuf.Client.EntityMove.prototype.setRotation = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protobuf.Client.EntityMove} returns this
 */
proto.Protobuf.Client.EntityMove.prototype.clearRotation = function() {
  return this.setRotation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protobuf.Client.EntityMove.prototype.hasRotation = function() {
  return jspb.Message.getField(this, 4) != null;
};


